# Generated by Django 3.0 on 2019-12-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reward',
            field=models.IntegerField(default=0),
        ),
    ]
